"""add cashbox entry audit

Revision ID: 70f29fdb45ad
Revises: 001
Create Date: 2026-02-08 20:00:38.502211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f29fdb45ad'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashbox_entry_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('edited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('edit_reason', sa.String(length=255), nullable=False),
    sa.Column('old_date', sa.Date(), nullable=True),
    sa.Column('old_amount_uzs', sa.Integer(), nullable=True),
    sa.Column('old_comment', sa.Text(), nullable=True),
    sa.Column('new_date', sa.Date(), nullable=True),
    sa.Column('new_amount_uzs', sa.Integer(), nullable=True),
    sa.Column('new_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_cashbox_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashbox_entry_audits_id'), 'cashbox_entry_audits', ['id'], unique=False)
    op.create_index(op.f('ix_advances_id'), 'advances', ['id'], unique=False)
    op.drop_index('ix_cashboxes_name', table_name='cashboxes')
    op.create_index(op.f('ix_cashboxes_id'), 'cashboxes', ['id'], unique=False)
    op.create_unique_constraint(None, 'cashboxes', ['name'])
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_company_transactions_id'), 'company_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_daily_cashbox_entries_id'), 'daily_cashbox_entries', ['id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_daily_cashbox_entries_id'), table_name='daily_cashbox_entries')
    op.drop_index(op.f('ix_company_transactions_id'), table_name='company_transactions')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_constraint(None, 'cashboxes', type_='unique')
    op.drop_index(op.f('ix_cashboxes_id'), table_name='cashboxes')
    op.create_index('ix_cashboxes_name', 'cashboxes', ['name'], unique=1)
    op.drop_index(op.f('ix_advances_id'), table_name='advances')
    op.drop_index(op.f('ix_cashbox_entry_audits_id'), table_name='cashbox_entry_audits')
    op.drop_table('cashbox_entry_audits')
    # ### end Alembic commands ###
